[package]
name = "turing"
version = "0.1.0"
authors = ["Itai Bar-Natan <itaibn3141@gmail.com>"]

[dependencies]
rand = "0.3.15"
cairo-rs = "0.1.2"
clap = "2.24.1"

[dependencies.gtk]
version = "0.1.2"
features = ["v3_10"]
